package net.imadz.infra.saga.serialization.converters

import akka.serialization.Serializers
import com.google.protobuf.ByteString
import net.imadz.infra.saga.StepExecutor.OperationResponse
import net.imadz.infra.saga.proto.saga_v2._
// [Key] Import OneOf helper classes generated by ScalaPB, matching your existing Proto structure (Result.Succeed / Result.Error)
import net.imadz.infra.saga.proto.saga_v2.OperationResponseCommandPO.Result.{Error, Succeed}
import net.imadz.infra.saga.serialization.SagaExecutorConverter

/**
 * SagaMessageProtoConverters
 * Adapts existing Proto: OperationResponseCommandPO (oneof result: succeed/error)
 */
trait SagaMessageProtoConverters extends SagaExecutorConverter {

  object OperationResponseConv {

    def toProto(domain: OperationResponse[_, _, _]): OperationResponseCommandPO = {
      val resultOneOf = domain.result match {
        case Right(result) =>
          // Serialize generic result R
          val resultRef = result.asInstanceOf[AnyRef]
          val serializer = serialization.findSerializerFor(resultRef)
          val bytes = serializer.toBinary(resultRef)
          val manifest = Serializers.manifestFor(serializer, resultRef)

          // [Adaptation] Use OperationSucceedCommandPO
          Succeed(OperationSucceedCommandPO(
            successMessageType = manifest, // Proto field name: successMessageType
            success = ByteString.copyFrom(bytes)
          ))

        case Left(error) =>
          // [Adaptation] Use OperationFailedCommandPO
          Error(OperationFailedCommandPO(
            error = Some(RetryableOrNotExceptionConv.toProto(error))
          ))
      }

      // Return Wrapper
      OperationResponseCommandPO(result = resultOneOf)
    }

    def fromProto(wrapper: OperationResponseCommandPO): OperationResponse[Any, Any, Any] = {
      wrapper.result match {
        case Succeed(p) => // p is OperationSucceedCommandPO
          val result = if (p.success.isEmpty) null else {
            serialization.deserialize(
              p.success.toByteArray,
              serialization.serializerFor(classOf[Any]).identifier,
              p.successMessageType // Proto field name: successMessageType
            ).get
          }
          import net.imadz.infra.saga.SagaParticipant.SagaResult
          OperationResponse(Right(result.asInstanceOf[SagaResult[Any]]), None)

        case Error(p) => // p is OperationFailedCommandPO
          val errPO = p.error.getOrElse(RetryableOrNotExceptionPO.defaultInstance)
          val error = RetryableOrNotExceptionConv.fromProto(errPO)
          OperationResponse(Left(error), None)

        case OperationResponseCommandPO.Result.Empty =>
          throw new IllegalArgumentException("OperationResponseCommandPO is empty!")
      }
    }
  }
}