@startuml
    participant Client
    participant SagaTransactionCoordinator as STC
    participant ExecutionPlan
    participant StepExecutor
    participant EventSourcedBehavior as ESB

    Client->>STC: StartTransaction(steps)
    STC->>ESB: Persist(TransactionStarted)
    ESB-->>STC: State Updated
    
    STC->>ExecutionPlan: new(steps)
    STC->>STC: startPhase(PreparePhase)

    loop For each StepGroup in phase
        STC->>ESB: Persist(StepGroupStarted)
        loop For each step in StepGroup
            STC->>StepExecutor: Start(step)
            StepExecutor-->>STC: StepResult (InternalStepResult)
            STC->>ESB: Persist(StepResultReceived)
        end
        STC->>STC: PhaseCompleted?
        alt Group Completed
            STC->>ESB: Persist(StepGroupSucceeded)
        end
    end

    alt All steps in Prepare successful
        STC->>ESB: Persist(PhaseSucceeded(PreparePhase))
        STC->>STC: startPhase(CommitPhase)
        ... Repeat StepGroup Loop for Commit ...
        STC->>ESB: Persist(TransactionCompleted)
        STC-->>Client: TransactionResult(successful=true)
    else Any step in Prepare/Commit failed
        STC->>ESB: Persist(PhaseFailed)
        STC->>STC: startPhase(CompensatePhase)
        ... Repeat StepGroup Loop for Compensate (Only successful steps) ...
        STC->>ESB: Persist(TransactionFailed)
        STC-->>Client: TransactionResult(successful=false)
    end
@enduml

@startuml
    participant Client
    participant SagaTransactionCoordinator
    participant StepExecutor

    Client->>SagaTransactionCoordinator: StartTransaction
    SagaTransactionCoordinator->>SagaTransactionCoordinator: executePhase(PreparePhase)

    loop For each step in PreparePhase
        SagaTransactionCoordinator->>StepExecutor: Start
        StepExecutor-->>SagaTransactionCoordinator: StepResult (Completed/Failed)
    end

    alt All steps successful
        SagaTransactionCoordinator->>SagaTransactionCoordinator: PhaseCompleted(PreparePhase)
        SagaTransactionCoordinator->>SagaTransactionCoordinator: executePhase(CommitPhase)

        loop For each step in CommitPhase
            SagaTransactionCoordinator->>StepExecutor: Start
            StepExecutor-->>SagaTransactionCoordinator: StepResult (Completed/Failed)
        end

        alt All steps successful
            SagaTransactionCoordinator->>SagaTransactionCoordinator: PhaseCompleted(CommitPhase)
            SagaTransactionCoordinator-->>Client: TransactionResult(successful=true)
        else Any step failed
            SagaTransactionCoordinator->>SagaTransactionCoordinator: PhaseFailed(CommitPhase)
            SagaTransactionCoordinator->>SagaTransactionCoordinator: executePhase(CompensatePhase)
        end
    else Any step failed
        SagaTransactionCoordinator->>SagaTransactionCoordinator: PhaseFailed(PreparePhase)
        SagaTransactionCoordinator->>SagaTransactionCoordinator: executePhase(CompensatePhase)
    end

    opt CompensatePhase
        loop For each step in CompensatePhase
            SagaTransactionCoordinator->>StepExecutor: Start
            StepExecutor-->>SagaTransactionCoordinator: StepResult (Completed/Failed)
        end

        SagaTransactionCoordinator->>SagaTransactionCoordinator: PhaseCompleted/PhaseFailed(CompensatePhase)
        SagaTransactionCoordinator-->>Client: TransactionResult(successful=false)
    end
@enduml
