akka {
  actor {
    serialization-identifiers {
      "net.imadz.infra.saga.serialization.SagaTransactionStepSerializer" = 1234
      "net.imadz.infra.saga.serialization.SagaSerializer" = 1235
    }

    serializers {
       saga-serializer = "net.imadz.infra.saga.serialization.SagaSerializer"
       saga-step-serializer = "net.imadz.infra.saga.serialization.SagaTransactionStepSerializer"
    }

    serialization-bindings {
       "net.imadz.infra.saga.StepExecutor$OperationResponse" =  saga-serializer
       "net.imadz.infra.saga.SagaTransactionStep" = saga-step-serializer
    }
  }
}
