name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Clear SBT caches
        run: sbt cleanCache
      - name: Run tests with detailed logging
        run: sbt -v test
      - name: Upload dependency graph
        uses: scalacenter/sbt-dependency-submission@v1
